### ISSUE TITLE
use this repo to store talk artifacts

### ISSUE THREAD

**Issue by Dowwie** [rust-nyc/meetups#6]
Are you open to the idea of broadening the goal of this repo so as to include talk artifacts?  That way, anyone who wants to see slides/code from prior talks could simply go to /rust-nyc and access materials.

**Comment by softprops** [comment]
It could. This is just an experiment and may go away entirely.

At this time there are 2 goals

1) reduce the amount of email thread tracking required to coordinate between speakers, hosts, and sponsors. 

2) to make that process more transparent so that other members can more easily opt into helping organize the meetup
